version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 30s
      timeout: 30s
      retries: 3

  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres:5432/mydb
    ports:
      - "3000:3000"
    restart: on-failure:3

  ngrok:
    image: wernight/ngrok
    command: ngrok http express-app:3000 -log=stdout -log-level=info -authtoken=${NGROK_AUTH}
    depends_on:
      - express-app
    environment:
      NGROK_PORT: express-app:3000
      NGROK_AUTH: ${NGROK_AUTH}
    

volumes:
  postgres_data: